// ============================================================
// Tool definitions for Claude API calls
// Step 1 uses tool use to force structured classification output
// ============================================================

import type Anthropic from "@anthropic-ai/sdk";

export const classifyCodeSessionTool: Anthropic.Tool = {
  name: "classify_code_session",
  description:
    "Analyzes a coding session between a developer and an AI assistant. " +
    "Extracts the prompt intent, identifies concepts involved, separates " +
    "AI-generated code from user modifications, and assesses the depth " +
    "of user modifications.",
  input_schema: {
    type: "object" as const,
    properties: {
      prompt_intent: {
        type: "string",
        description:
          "A concise summary of what the developer was trying to accomplish",
      },
      concepts_involved: {
        type: "array",
        items: { type: "string" },
        description:
          "Programming concepts present in the session (e.g., async/await, " +
          "state management, API design, error handling, algorithms, testing, " +
          "CSS layout, database queries, authentication, type safety)",
      },
      ai_generated_blocks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            code: { type: "string", description: "The AI-generated code" },
            language: {
              type: "string",
              description: "Programming language",
            },
            line_start: {
              type: "number",
              description: "Approximate starting line",
            },
            line_end: {
              type: "number",
              description: "Approximate ending line",
            },
          },
          required: ["code", "language", "line_start", "line_end"],
        },
        description: "Code blocks that were generated by the AI assistant",
      },
      user_modifications: {
        type: "array",
        items: {
          type: "object",
          properties: {
            original: {
              type: "string",
              description: "The original AI-generated code",
            },
            modified: {
              type: "string",
              description: "What the user changed it to",
            },
            description: {
              type: "string",
              description: "What the modification accomplishes",
            },
          },
          required: ["original", "modified", "description"],
        },
        description:
          "Modifications the developer made to the AI-generated code",
      },
      modification_depth: {
        type: "string",
        enum: ["none", "cosmetic", "structural", "rewrite"],
        description:
          "Overall depth of modifications: none (accepted as-is), " +
          "cosmetic (variable names, formatting), structural (logic changes, " +
          "error handling added), rewrite (fundamental restructuring)",
      },
    },
    required: [
      "prompt_intent",
      "concepts_involved",
      "ai_generated_blocks",
      "user_modifications",
      "modification_depth",
    ],
  },
};

export const generateIdentityMapTool: Anthropic.Tool = {
  name: "generate_identity_map",
  description:
    "Generates a structured skill identity map that categorizes the developer's " +
    "skills into three zones based on their interaction with AI-generated code.",
  input_schema: {
    type: "object" as const,
    properties: {
      your_ground: {
        type: "array",
        items: {
          type: "object",
          properties: {
            skill: { type: "string" },
            confidence: {
              type: "number",
              description: "0.0-1.0 confidence that this is a genuine skill",
            },
            evidence: {
              type: "string",
              description:
                "Specific evidence from the session supporting this assessment",
            },
          },
          required: ["skill", "confidence", "evidence"],
        },
        description:
          "Skills the developer genuinely understands (confidence >= 0.7)",
      },
      growing_edge: {
        type: "array",
        items: {
          type: "object",
          properties: {
            skill: { type: "string" },
            confidence: { type: "number" },
            evidence: { type: "string" },
          },
          required: ["skill", "confidence", "evidence"],
        },
        description:
          "Skills showing partial understanding (confidence 0.4-0.69)",
      },
      ai_zone: {
        type: "array",
        items: {
          type: "object",
          properties: {
            skill: { type: "string" },
            confidence: { type: "number" },
            evidence: { type: "string" },
          },
          required: ["skill", "confidence", "evidence"],
        },
        description: "Skills fully delegated to AI (confidence < 0.4)",
      },
      session_summary: {
        type: "string",
        description:
          "A brief, encouraging summary of the developer's skill identity " +
          "based on this session. Growth-oriented tone.",
      },
    },
    required: ["your_ground", "growing_edge", "ai_zone", "session_summary"],
  },
};

export const generateChallengesTool: Anthropic.Tool = {
  name: "generate_challenges",
  description:
    "Generates targeted micro-challenges based on the developer's identity map. " +
    "Challenges are AI-collaborative — the developer uses AI but must demonstrate " +
    "understanding first.",
  input_schema: {
    type: "object" as const,
    properties: {
      challenges: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { type: "string", description: "Unique challenge identifier" },
            title: {
              type: "string",
              description:
                "Engaging, inviting challenge title (not intimidating)",
            },
            description: {
              type: "string",
              description:
                "What this challenge helps the developer explore",
            },
            code_snippet: {
              type: "string",
              description:
                "A code snippet with an intentional issue or incomplete implementation",
            },
            language: { type: "string", description: "Programming language" },
            instructions: {
              type: "array",
              items: { type: "string" },
              description:
                "Step-by-step instructions. First steps require understanding " +
                "(no AI). Later steps allow AI collaboration with supervision.",
            },
            skill_target: {
              type: "string",
              description: "The skill this challenge targets",
            },
            target_zone: {
              type: "string",
              enum: ["growing_edge", "ai_zone"],
              description: "Which zone this skill currently lives in",
            },
            difficulty: {
              type: "string",
              enum: ["approachable", "moderate", "stretch"],
            },
          },
          required: [
            "id",
            "title",
            "description",
            "code_snippet",
            "language",
            "instructions",
            "skill_target",
            "target_zone",
            "difficulty",
          ],
        },
      },
      rationale: {
        type: "string",
        description:
          "Explanation of why these challenges were chosen and how they connect " +
          "to the developer's growth areas",
      },
    },
    required: ["challenges", "rationale"],
  },
};
